cloudoptim/qptestflowcore

QPCore/Model/DataBaseModel/TestFlows/TestFlow.cs
Add resource type column into TestFlowStep
=> add resource type field into step object

.gitignore, QPCore/AutoMapper/MappingProfile.cs, QPCore/Controllers/TestFlowController.cs, QPCore/Model/DataBaseModel/TestFlows/TestFlow.cs, QPCore/Model/DataBaseModel/TestFlows/TestFlowBaseDTO.cs, QPCore/Model/DataBaseModel/TestFlows/TestFlowDTO.cs, QPCore/QPCore.csproj, QPCore/Service/TestFlowService.cs, QPCore/Startup.cs
when updating, we need merge them to one field is steps: [{datariven},{step}. {resource}]
=> Group steps to Data Driven, Data Resource, Step

QPCore/Controllers/WebElementController.cs, QPCore/Model/WebElement/CheckingWebElementDTO.cs, QPCore/Model/WebElement/CheckingWebElementItem.cs, QPCore/Service/WebElementService.cs
API to  check web element name , If element name exists return true and else return false.
For example: 
Input: 
{
"pageId": 7,
"elementNames": [
"password",
"username",
"login"  ]
}
Output:        
[
{
"pageId": "7",
"name": "password",
"isExisted": true
},
{
"pageId": "7",
"name": "username",
"isExisted": true
},
{
"pageId": "7",
"name": "login",
"isExisted": false
}
]
=> add api checking web element on page

QPCore/Startup.cs, QPCore/appsettings.json
- Change db name
- Fixed allow cors
=> Change db name and fixed enable cors

QPCore/Model/DataBaseModel/TestFlows/TestFlowBaseDTO.cs
Fixed nullable on LockedBy from TestFlow table when you get all testflow
=> allow null on LockBy property

QPCore/Model/Common/CheckLockingDTO.cs, QPCore/Service/TestFlowService.cs, QPCore/appsettings.Development.json
- Add LockedById, LockedByName ([FirstName LastName]), LockedByEmail
=> Add user information for checking locking testflow

QPCore/Service/TestPlanTestCaseService.cs
Add distinct testcase list when creating testplantestcaseassociate
=> add distinct value for testcase id

QPCore/Model/Common/Validations/IsNotNumberAttribute.cs, QPCore/Model/TestPlans/CreateTestPlanRequest.cs, QPCore/Model/TestPlans/EditTestPlanRequest.cs, QPCore/Model/TestPlans/TestPlanResponse.cs
Add validation on TestPlan
- Name should not be a number
- ParentId should be different current id
- Add Fullname to TestPlanResponse model
=> Dev add validation for name

QPCore/Service/TestPlanService.cs, QPCore/Service/TestPlanTestCaseService.cs
- Only return parent test plans
- Order by descending for testplan and testplan assignment
=> Improve order by and get all parents testplan

QPCore/Helpers/TokenException.cs, QPCore/Middleware/ErrorHandlerMiddleware.cs, QPCore/Service/AccountService.cs
When user sends an invalid refresh token, he will get back 409 code
=> return code 409 when the refresh token is invalid

QPCore/Model/DataBaseModel/AppFeature.cs
Fixed null value on app feature api /api/appfeature
=> fixed null value on parentfeatureid

QPCore/Model/WebElement/CheckingWebElementDTO.cs, QPCore/Model/WebElement/CheckingWebElementItem.cs, QPCore/Model/WebElement/WebElementItem.cs, QPCore/Service/WebElementService.cs
=> Dev fix check element name

QPCore/AutoMapper/MappingProfile.cs, QPCore/Controllers/WebElementController.cs, QPCore/Model/DataBaseModel/EditWebElementRequest.cs, QPCore/Service/WebElementService.cs, QPCore/Startup.cs
Add API to edit web element with pageid and group id
=> add edit web element

QPCore/Data/QPContext.cs, QPCore/Migrations/20210603012745_fixed allow null for updated date in orguser.Designer.cs, QPCore/Migrations/20210603012745_fixed allow null for updated date in orguser.cs, QPCore/Model/DataBaseModel/TestFlows/TestFlow.cs
- Fixed an error in Register api
- Fixed null rows in steps api
=> fixed null rows in step and allow null on updated date on orguser

QPCore/Controllers/WebPageController.cs, QPCore/Model/Common/ExistedBulkResponse.cs, QPCore/Model/Common/ExistedResponse.cs, QPCore/Model/WebPages/ExistedBulkNameRequest.cs, QPCore/Service/BaseGroupService.cs, QPCore/Service/BaseService.cs, QPCore/Service/Interfaces/IWebPageService.cs, QPCore/Service/WebPageService.cs
Add existed id into response data
{
"isExisted": true,
"existedId": 2
}
=> add id into response of existed api

QPCore/Controllers/WebElementController.cs, QPCore/Controllers/WebPageController.cs, QPCore/Data/Enitites/WebElement.cs, QPCore/Data/Enitites/WebPage.cs, QPCore/Data/IRepository.cs, QPCore/Data/QPContext.cs, QPCore/Data/Repository.cs, QPCore/Migrations/20210607153345_update webelement table.Designer.cs, QPCore/Migrations/20210607153345_update webelement table.cs, QPCore/Model/DataBaseModel/WebElement.cs, QPCore/Model/WebPages/BulkUpsertResponse.cs, QPCore/QPCore.csproj, QPCore/Service/Interfaces/IWebPageService.cs, QPCore/Service/WebElementService.cs, QPCore/Service/WebPageService.cs
POST /api/webpages/bulk
Request:
{
"groupId": 39, 
"nameList": [
"pi",
"load",
"load2"
]
}
Response:
[
{
"id": 113,
"groupId": 39,
"name": "pi"
},
{
"id": 116,
"groupId": 39,
"name": "load"
},
{
"id": 118,
"groupId": 39,
"name": "load2"
}
]
=> add api for upsert webpage

QPCore/Data/Enitites/WebElement.cs, QPCore/Data/QPContext.cs, QPCore/Service/WebElementService.cs
=> fixed bug don't save ivalue

QPCore/Data/Enitites/TestFlowCategory.cs, QPCore/Data/QPContext.cs, QPCore/Migrations/20210610050633_add type column into testflowcategory table.Designer.cs, QPCore/Migrations/20210610050633_add type column into testflowcategory table.cs, QPCore/Model/TestFlowCategories/CreateTestFlowCategoryRequest.cs, QPCore/Service/TestFlowCategoryService.cs
Add type into test category
Type: Area | Category
=> update add type to test flow category

QPCore/AutoMapper/MappingProfile.cs, QPCore/Controllers/TestFlowCategoryAssocsController.cs, QPCore/Model/TestFlowCategoryAssocs/BulkCreateRequest.cs, QPCore/Model/TestFlowCategoryAssocs/TestFlowCategoryAssocResponse.cs, QPCore/Service/Interfaces/ITestFlowCategoryAssocService.cs, QPCore/Service/TestFlowCategoryAssocService.cs
POST: {{HOST}}/api/testflowcategoryassocs/bulk
{
"testcaseIdList": [13,15,16,18],
"categoryIdList": [6,7,8]
}
=> add bulk insert for categories assignment

QPCore/Service/TestFlowCategoryAssocService.cs
=> fixed delete case

QPCore/AutoMapper/MappingProfile.cs, QPCore/Controllers/IntegrationsController.cs, QPCore/Model/Integrations/IntegrationResponse.cs, QPCore/Service/IntegrationService.cs, QPCore/Service/Interfaces/IIntegrationService.cs
- Add PAT to response 
- Add validation
=> add PAT into response
